fun main() {
    throw Exception("This is an Exception")
}